/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author susuc
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botaotabuada = new javax.swing.JButton();
        botaoimc = new javax.swing.JButton();
        botaonotas = new javax.swing.JButton();
        botaotemp = new javax.swing.JButton();
        botaolistaf = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelnome = new javax.swing.JLabel();
        botaoad = new javax.swing.JButton();
        botaocalculadora = new javax.swing.JButton();
        botaocaracter = new javax.swing.JButton();
        botaoarea = new javax.swing.JButton();
        botaodias = new javax.swing.JButton();
        botaohipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Every(thing)");

        botaotabuada.setText("Tabuada");

        botaoimc.setText("IMC");
        botaoimc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoimcActionPerformed(evt);
            }
        });

        botaonotas.setText("Nota");

        botaotemp.setText("Conversão Temperatura");

        botaolistaf.setText("Lista de Filmes");

        labelnome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelnome.setText("Olá, ");

        botaoad.setText("Acréscimo e Desconto");

        botaocalculadora.setText("Calculadora");
        botaocalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaocalculadoraActionPerformed(evt);
            }
        });

        botaocaracter.setText("Cálculo de Caracteres");

        botaoarea.setText("Cálculo de Área");

        botaodias.setText("Dias de Vida");

        botaohipo.setText("Hipotenusa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(240, 240, 240))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(116, 116, 116)
                        .addComponent(labelnome, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaotabuada)
                                .addGap(18, 18, 18)
                                .addComponent(botaotemp)
                                .addGap(18, 18, 18)
                                .addComponent(botaoad)
                                .addGap(18, 18, 18)
                                .addComponent(botaoarea)
                                .addGap(18, 18, 18)
                                .addComponent(botaohipo))
                            .addComponent(botaodias)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(botaoimc)
                                .addGap(18, 18, 18)
                                .addComponent(botaonotas)
                                .addGap(18, 18, 18)
                                .addComponent(botaolistaf)
                                .addGap(18, 18, 18)
                                .addComponent(botaocalculadora)
                                .addGap(18, 18, 18)
                                .addComponent(botaocaracter)))
                        .addGap(110, 110, 110))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(labelnome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaotabuada)
                    .addComponent(botaotemp)
                    .addComponent(botaoad)
                    .addComponent(botaoarea)
                    .addComponent(botaohipo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoimc)
                    .addComponent(botaonotas)
                    .addComponent(botaolistaf)
                    .addComponent(botaocalculadora)
                    .addComponent(botaocaracter))
                .addGap(18, 18, 18)
                .addComponent(botaodias)
                .addContainerGap(314, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoimcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoimcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoimcActionPerformed

    private void botaocalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaocalculadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaocalculadoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoad;
    private javax.swing.JButton botaoarea;
    private javax.swing.JButton botaocalculadora;
    private javax.swing.JButton botaocaracter;
    private javax.swing.JButton botaodias;
    private javax.swing.JButton botaohipo;
    private javax.swing.JButton botaoimc;
    private javax.swing.JButton botaolistaf;
    private javax.swing.JButton botaonotas;
    private javax.swing.JButton botaotabuada;
    private javax.swing.JButton botaotemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelnome;
    // End of variables declaration//GEN-END:variables
}
